### ISSUE TITLE
Unable to create the manual booking order when the multiple time slot addon is active

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Multiple-Time-Slot-addon#40]
Unable to create the manual booking order when the multiple time slot addon is active.

Screenshot: https://prnt.sc/oqubsd

On the client site, some error in the console is shown. Could not take a screenshot now as we have applied the fix on his site.

Ticket: https://tychesoftwares.freshdesk.com/a/tickets/9360

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking-1.7/commit/e1015e847f73aa08a83a5ef0d4ad09fd86b6f9a8 commit hence closing it. Only one timeslot can be manually booked as when selecting multiple timeslots it is not allowing which is currently difficult to fix in the current code structure. Hence made partial fix by allowing to add a manual booking for a single timeslot.
